#!/usr/bin/env python3
"""sorge robomp — ON 스위치. GitHub 이슈 훅 → stock RobOMP 루프.

WHY THIS EXISTS
----------------
`sorge#22` Phase 0: 이슈 사건이 담당자 턴을 깨우고 판정이 남는다. 하네스는
새로 짓지 않는다 — OMP 의 RobOMP (`~/repos/3rd/pi/oh-my-pi/python/robomp`) 가
입구다. 이 스크립트는 그 위에 얹는 **손잡이**다: 켜고/끄고/보는 것만 한다.

**프로파일은 우리가 정의하지 않는다.** stock RobOMP 가 주는 흐름(분류 → 댓글
→ 수정 → 브랜치 → PR)을 그대로 쓴다. 2026-09-15 GLG 판정: fork 를 고치면
omp 버전업이 막힌다 — 좁히려던 1188줄을 되돌리고 `sorge-label` 프로파일은
곁가지 `sorge-label-profile` 에만 남겼다. 여기서 정하는 것은 **설정뿐**이다:
어느 리포(대장 allowlist), 어느 모델(API 키로 닿는 것), 어느 봇 이름.

경계 — 이 스크립트가 절대 하지 않는 것
--------------------------------------
- LEDGER.md 파싱을 다시 구현하지 않는다. `board.ledger_houses()` 를 그대로
  쓴다 — 대장 파싱은 한 곳에만 있어야 한다(이 집의 규율).
- fork(oh-my-pi) 소스를 고치지 않는다. venv 에 editable 설치만 한다.
- 비밀값을 파일 밖으로 내지 않는다. `pass` 에서 읽어 0600 파일에만 쓰고,
  화면에는 절대 찍지 않는다(dry-run 포함).
"""
import argparse
import json
import os
import re
import secrets
import shlex
import signal
import socket
import sqlite3
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

# 대장 파싱은 board.py 가 이미 든다 — 여기서 다시 만들지 않는다. 심링크로
# 도달해도 뿌리가 흔들리지 않는 이유는 board.py 의 docstring(realpath 8/8)과
# 같다.
HERE = os.path.dirname(os.path.realpath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)
import board  # noqa: E402

OWNER = board.OWNER

HOME = Path.home()
CONFIG_DIR = HOME / ".config" / "sorge"
STATE_DIR = HOME / ".local" / "state" / "sorge" / "robomp"
LOG_DIR = STATE_DIR / "logs"
DATA_DIR = HOME / ".local" / "share" / "sorge" / "robomp"
CACHE_DIR = HOME / ".cache" / "sorge"
VENV_DIR = CACHE_DIR / "robomp-venv"
ROBOMP_ENV = CONFIG_DIR / "robomp.env"
PROXY_ENV = CONFIG_DIR / "robomp-proxy.env"

ORCH_HOST = "127.0.0.1"
ORCH_PORT = 8080
PROXY_HOST = "127.0.0.1"
PROXY_PORT = 8081

DEFAULT_OMP_ROOT = HOME / "repos" / "3rd" / "pi" / "oh-my-pi"

# 루프가 쓰는 모델. 호스트 구독(`~/.omp/agent/agent.db`)은 자식이 못 본다 —
# stock robomp 는 agent_dir 을 자식에게 넘기지 않고, 자식은 격리 XDG 로 뜬다.
# 그래서 여기 있는 것은 반드시 **API 키로 닿는 provider** 여야 한다.
# 2026-09-15 실측: anthropic 401 · openai 401 · deepseek 200 · gemini 200.
MODEL = "deepseek/deepseek-v4-pro"
THINKING = "high"
PROVIDER_KEY_ENV = "DEEPSEEK_API_KEY"

# 봇 계정 토큰: orchestrator/gh-proxy 가 매일 쓰는 것. 판정은 sorge-bot 이름으로
# 남아야 한다. classic: `gh webhook forward` 만 (admin:repo_hook 이 거기에만
# 있고, 후크 등록은 리포 소유자인 GLG 의 권한이다).
BOT_LOGIN = "sorge-bot"
PASS_PAT_BOT = "api/github/sorge-bot/pat"
PASS_PAT_CLASSIC = "api/github/junghan0611/forge/pat"

SECRET_KEYS = {"GITHUB_WEBHOOK_SECRET", "ROBOMP_GH_PROXY_HMAC_KEY", "GITHUB_TOKEN", PROVIDER_KEY_ENV}


class Halt(Exception):
    """`on --go` 가 이 자리에서 멈춘다 — 사유는 메시지에 있다."""


# ── 작은 도구들 ──────────────────────────────────────────────────────────


def omp_root() -> Path:
    return Path(os.environ.get("SORGE_OMP_ROOT", str(DEFAULT_OMP_ROOT))).expanduser()


def sh(cmd, **kw):
    return subprocess.run(cmd, capture_output=True, text=True, **kw)


def port_alive(host, port, timeout=1.0):
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True
    except OSError:
        return False


def pidfile_path(name):
    return STATE_DIR / f"{name}.pid"


def read_pidfile(name):
    p = pidfile_path(name)
    if not p.exists():
        return None
    try:
        return int(p.read_text().strip())
    except ValueError:
        return None


def pid_alive(pid):
    return pid is not None and Path(f"/proc/{pid}").exists()


def proc_alive(name):
    pid = read_pidfile(name)
    return pid_alive(pid), pid


def forward_name(repo):
    return "webhook-forward-" + repo.replace("/", "-")


def parse_env_file(path):
    out = {}
    if not path.exists():
        return out
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        out[k.strip()] = v.strip()
    return out


def render_env_file(values):
    lines = [
        "# sorge robomp — generated by ./run.sh robomp on --go. Do not hand-edit (a rerun overwrites it).",
        "",
    ]
    lines += [f"{k}={v}" for k, v in values.items()]
    lines.append("")
    return "\n".join(lines)


def write_env_file(path, values):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_env_file(values), encoding="utf-8")
    os.chmod(path, 0o600)


def allowlist_repos():
    """대장 `배정` 리포 → `owner/repo` 목록. board.py 의 판정을 그대로 쓴다."""
    houses = board.ledger_houses()
    return [f"{OWNER}/{repo}" for repo in sorted(houses)]


def pass_show(path):
    r = sh(["pass", "show", path])
    if r.returncode != 0:
        raise RuntimeError(f"pass show {path} failed: {(r.stderr or '').strip() or ('exit ' + str(r.returncode))}")
    val = r.stdout.strip()
    if not val:
        raise RuntimeError(f"pass show {path} returned an empty value")
    return val


def gh_api(token, method, path, body=None):
    """GitHub REST 한 번. 토큰은 헤더로만 간다 — argv 에 실으면 같은 사용자의
    다른 프로세스가 `ps` 로 줍는다."""
    data = json.dumps(body).encode("utf-8") if body is not None else None
    req = urllib.request.Request(
        f"https://api.github.com{path}",
        data=data,
        method=method,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "User-Agent": "sorge-robomp",
            "Content-Type": "application/json",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            return resp.status, json.loads(resp.read() or b"null")
    except urllib.error.HTTPError as exc:
        try:
            return exc.code, json.loads(exc.read() or b"null")
        except ValueError:
            return exc.code, None
    except urllib.error.URLError as exc:
        raise RuntimeError(f"GitHub unreachable: {exc.reason}") from exc


def bot_writable_repos(dry, token, repos):
    """대장 대상 중 **봇이 실제로 판정을 쓸 수 있는 집**만 남긴다.

    읽기는 신호가 아니다. 대상 리포가 전부 public 이라 토큰이 없어도 200 이
    나온다. 쓰기만 신호이고, 쓰기는 두 가지로 막힌다:

    1. **토큰 종류.** fine-grained PAT 는 발급 계정이 *소유한* 리포에만 권한을
       줄 수 있다. collaborator 로 push 권한이 있어도 GLG 소유 리포에는
       `403 Resource not accessible by personal access token` 이 난다
       (2026-09-15 실측). classic + `public_repo` 여야 한다.
    2. **초대.** 초대되지 않은 집은 `404 Not Found` 다 — 권한 문제가 아니라
       봇이 그 집에 아예 없는 것이다.

    둘을 갈라 보여주고, 쓸 수 있는 집만 allowlist 로 넘긴다. 초대 안 된 집을
    allowlist 에 남기면 그 집 이슈마다 턴이 열려 403/404 로 죽는다 — 대장은
    대상을 정하지만 **닿을 수 있는지는 대장이 모른다.**
    """
    status, who = gh_api(token, "GET", "/user")
    login = (who or {}).get("login") if status == 200 else None
    check(
        dry,
        login == BOT_LOGIN,
        f"token owner = {login}",
        f"token owner is {login or f'unknown({status})'} — must be {BOT_LOGIN}",
    )

    writable, missing = [], []
    for repo in repos:
        status, info = gh_api(token, "GET", f"/repos/{repo}")
        if status == 200 and (info or {}).get("permissions", {}).get("push"):
            writable.append(repo)
        elif status == 200:
            # public 이라 읽기는 되지만 collaborator 가 아니다.
            missing.append((repo, "not invited (read-only)"))
        elif status == 404:
            missing.append((repo, "repo missing or private and not invited (404)"))
        else:
            missing.append((repo, f"unreachable ({status})"))

    if writable:
        # 한 집에서 무변경 PATCH 로 라벨 쓰기를 실제로 확인한다. push=true 가
        # 곧 이슈 쓰기라는 추론에 기대지 않는다 — 토큰 스코프가 좁으면
        # push 권한이 있어도 거부될 수 있다.
        #
        # 그러나 **dry-run 은 밖에 쓰지 않는다.** 무변경이라도 PATCH 는 쓰기이고,
        # GitHub 은 그것을 감사로그에 남긴다. dry-run 의 계약은 「아무것도 안
        # 바뀐다」이지 「같은 값으로 바뀐다」가 아니다 (terra 검수, 2026-09-15).
        probe = writable[0]
        status, labels = gh_api(token, "GET", f"/repos/{probe}/labels?per_page=1")
        if status != 200 or not isinstance(labels, list) or not labels:
            check(dry, False, "", f"{probe} can't read label list ({status})")
        elif dry:
            print(f"   [dry-run] would verify label write on {probe} with a no-op PATCH (not sent — dry-run writes nothing)")
        else:
            current = labels[0]
            body = {k: current[k] for k in ("name", "color", "description") if k in current}
            status, err = gh_api(token, "PATCH", f"/repos/{probe}/labels/{current['name']}", body)
            check(
                dry,
                status == 200,
                f"{probe} label write ok (no-op PATCH 200)",
                f"{probe} label write rejected ({status} {(err or {}).get('message', '')}) — "
                f"check that {BOT_LOGIN}'s token is classic + `public_repo`",
            )

    for repo, why in missing:
        print(f"   · excluded {repo} — {why}")
    check(
        dry,
        bool(writable),
        f"repos the bot can write {len(writable)}/{len(repos)} → {','.join(writable)}",
        f"{BOT_LOGIN} can't write to any of the {len(repos)} ledger-targeted repos — invite it as a collaborator first",
    )
    return writable


FORWARDER_HOOK_HOST = "webhook-forwarder.github.com"


def forwarder_hooks(token, repo):
    """그 리포에 남아 있는 `gh webhook forward` relay 훅의 id 들.

    forward 는 리포에 훅을 만들고 프로세스가 죽어도 남긴다. 남은 훅은 다음
    `on` 을 `422 Hook already exists` 로 즉사시키고, 배달은 아무도 안 받는
    relay 로 흘러간다. URL 호스트로만 골라낸다 — 사람이 만든 훅은 절대
    건드리지 않는다.
    """
    status, hooks = gh_api(token, "GET", f"/repos/{repo}/hooks")
    if status != 200 or not isinstance(hooks, list):
        return []
    return [h["id"] for h in hooks if FORWARDER_HOOK_HOST in str((h.get("config") or {}).get("url", ""))]



def check(dry, cond, ok_msg, fail_msg):
    """전제 하나를 찍는다. `--go` 에서 실패하면 그 자리에서 멈춘다."""
    if cond:
        print(f"   ✓ {ok_msg}")
        return True
    print(f"   ✗ {fail_msg}")
    if not dry:
        raise Halt(fail_msg)
    return False


def attempt(dry, label, fn):
    """fn() 을 실행하고 영수증을 찍는다. `--go` 에서 실패하면 멈춘다."""
    try:
        result = fn()
        print(f"   ✓ {label}")
        return result
    except Exception as exc:  # noqa: BLE001 — 원인 그대로 사유에 싣는다
        print(f"   ✗ {label} failed: {exc}")
        if not dry:
            raise Halt(f"{label} failed: {exc}") from exc
        return None


def launch(cmd, *, cwd, env, log_path, pidname):
    log_path.parent.mkdir(parents=True, exist_ok=True)
    pidfile_path(pidname).parent.mkdir(parents=True, exist_ok=True)
    logf = open(log_path, "ab")
    proc = subprocess.Popen(
        cmd,
        cwd=str(cwd),
        env=env,
        stdout=logf,
        stderr=subprocess.STDOUT,
        stdin=subprocess.DEVNULL,
        start_new_session=True,  # setsid 동격 — 이 세션이 끝나도 산다
    )
    pidfile_path(pidname).write_text(str(proc.pid))
    return proc.pid


def wait_port(host, port, timeout, label):
    deadline = time.time() + timeout
    while time.time() < deadline:
        if port_alive(host, port):
            print(f"   ✓ {label} ready — {host}:{port}")
            return
        time.sleep(0.5)
    raise Halt(f"{label} didn't open {host}:{port} within {timeout}s — check the log")


def wait_http_ok(url, timeout, label):
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            with urllib.request.urlopen(url, timeout=2) as resp:  # noqa: S310
                if resp.status < 500:
                    print(f"   ✓ {label} ready — {url} → {resp.status}")
                    return
        except (urllib.error.URLError, OSError):
            pass
        time.sleep(0.5)
    raise Halt(f"{label} didn't respond at {url} within {timeout}s — check the log")


def wait_log(log_path, pattern, timeout, label):
    deadline = time.time() + timeout
    while time.time() < deadline:
        if log_path.exists():
            text = log_path.read_text(encoding="utf-8", errors="replace")
            if pattern.search(text):
                print(f"   ✓ {label} ready — log: {log_path}")
                return
        time.sleep(0.5)
    raise Halt(f"{label} didn't signal ready within {timeout}s — check the log: {log_path}")


# ── status ───────────────────────────────────────────────────────────────


def cmd_status(_args):
    print("━━ sorge robomp · status ━━\n")

    proxy_up = port_alive(PROXY_HOST, PROXY_PORT)
    orch_up = port_alive(ORCH_HOST, ORCH_PORT)
    print(f"  gh-proxy      {'up' if proxy_up else 'down'} — {PROXY_HOST}:{PROXY_PORT}")
    print(f"  orchestrator  {'up' if orch_up else 'down'} — {ORCH_HOST}:{ORCH_PORT}")

    cfg = parse_env_file(ROBOMP_ENV)
    print()
    if not cfg:
        print(f"  no config — {ROBOMP_ENV} doesn't exist yet. Run `./run.sh robomp on --go` to turn it on.")
        repos = []
    else:
        print(f"  profile       stock full (we don't define our own profile — so an omp version bump doesn't get blocked)")
        print(f"  model         {cfg.get('ROBOMP_MODEL', '?')}  (thinking={cfg.get('ROBOMP_THINKING', '?')})")
        print(f"  provider key  {PROVIDER_KEY_ENV} {'present' if cfg.get(PROVIDER_KEY_ENV) else 'missing — the judge turn will fail authentication'}")
        print(f"  bot login     {cfg.get('ROBOMP_BOT_LOGIN', '?')}")
        allow = cfg.get("ROBOMP_REPO_ALLOWLIST", "")
        print(f"  allowlist     {allow or '(empty)'}")
        repos = [r for r in allow.split(",") if r]

    print()
    if not cfg:
        print("  gh webhook forward: no targets (no config)")
    elif not repos:
        print("  gh webhook forward: no targets (allowlist is empty)")
    else:
        print("  gh webhook forward:")
        for repo in repos:
            alive, pid = proc_alive(forward_name(repo))
            print(f"    {repo:<32} {'up (pid ' + str(pid) + ')' if alive else 'down'}")

    sqlite_path = Path(cfg["ROBOMP_SQLITE_PATH"]) if cfg.get("ROBOMP_SQLITE_PATH") else (DATA_DIR / "robomp.sqlite")
    print()
    if not sqlite_path.exists():
        print(f"  no recent events — sqlite doesn't exist yet ({sqlite_path})")
    else:
        try:
            con = sqlite3.connect(f"file:{sqlite_path}?mode=ro", uri=True)
            con.row_factory = sqlite3.Row
            rows = con.execute(
                "SELECT delivery_id, event_type, repo, issue_key, state, received_at "
                "FROM events ORDER BY received_at DESC LIMIT 5"
            ).fetchall()
            con.close()
        except sqlite3.Error as exc:
            print(f"  event query failed: {sqlite_path} — {exc}")
            rows = None
        if rows is not None:
            if rows:
                print(f"  recent events (up to 5, {sqlite_path}):")
                for row in rows:
                    print(
                        f"    {row['received_at']}  {row['state']:<8} {row['event_type']:<16} "
                        f"{row['repo'] or '-':<28} {row['issue_key'] or ''}"
                    )
            else:
                print(f"  no recent events — the events table is empty ({sqlite_path})")

    if not proxy_up and not orch_up and not cfg:
        print("\n  Nothing is running.")


# ── allowlist ────────────────────────────────────────────────────────────


def cmd_allowlist(_args):
    repos = allowlist_repos()
    print(f"━━ sorge robomp · allowlist · {len(repos)} ledger-assigned repos ━━\n")
    for r in repos:
        print(f"  {r}")
    print()
    print(f"ROBOMP_REPO_ALLOWLIST={','.join(repos)}")


# ── on ───────────────────────────────────────────────────────────────────


def _on_steps(dry, only=""):
    root = omp_root()
    robomp_src = root / "python" / "robomp"
    omprpc_src = root / "python" / "omp-rpc"

    print("1) fork check")
    check(
        dry,
        robomp_src.is_dir() and omprpc_src.is_dir(),
        f"{root}  (both python/robomp and python/omp-rpc exist)",
        f"{root} is missing python/robomp or python/omp-rpc — override with SORGE_OMP_ROOT",
    )

    print("\n2) gh extension check")
    ext = sh(["gh", "extension", "list"])
    has_webhook_ext = ext.returncode == 0 and "gh webhook" in ext.stdout
    check(
        dry,
        has_webhook_ext,
        "gh webhook extension installed",
        "gh webhook extension missing — `gh extension install cli/gh-webhook`",
    )

    print("\n3) venv setup")
    pyexe = str(VENV_DIR / "bin" / "python")
    pip = str(VENV_DIR / "bin" / "pip")
    if VENV_DIR.exists():
        print(f"   ✓ already exists: {VENV_DIR}")
    else:
        print(f"   {'would create' if dry else 'creating'}: python3 -m venv {VENV_DIR}")
        print(f"   {'would install' if dry else 'installing'}: pip install -e {omprpc_src}  (pip only — AGENTS.md)")
        print(f"   {'would install' if dry else 'installing'}: pip install -e {robomp_src}")
        if not dry:
            r = sh(["python3", "-m", "venv", str(VENV_DIR)])
            if r.returncode != 0:
                raise Halt(f"venv creation failed: {r.stderr.strip()}")
            for target in (omprpc_src, robomp_src):
                r = sh([pip, "install", "-e", str(target)])
                if r.returncode != 0:
                    raise Halt(f"pip install -e {target} failed: {r.stderr.strip()[-800:]}")
            print(f"   ✓ venv ready: {VENV_DIR}")

    print("\n4) ledger → allowlist (reusing board.ledger_houses())")
    # board.py 가 대장을 못 읽으면 여기서 sys.exit 로 바로 멈춘다 — 빈 대장을
    # "빚 0" 처럼 조용히 삼키지 않는 것이 board.py 의 규율이고, 여기서도 그대로다.
    ledger_repos = allowlist_repos()
    check(dry, len(ledger_repos) > 0, f"{len(ledger_repos)} assigned → {','.join(ledger_repos)}", "no repos assigned in the ledger — check LEDGER.md")
    # 대장은 대상을 정하고, 봇 토큰은 그중 닿을 수 있는 곳을 정한다. allowlist
    # 는 둘의 교집합이어야 한다 — 초대 안 된 집을 남기면 그 집 이슈마다 턴이
    # 열려 404 로 죽는다.
    bot_token = attempt(dry, f"pass {PASS_PAT_BOT} read", lambda: pass_show(PASS_PAT_BOT))
    allow_repos = bot_writable_repos(dry, bot_token, ledger_repos) if bot_token else ledger_repos

    # 좁은 시작. 대장은 그대로 두고 **이번 기동만** 몇 집으로 줄인다 — 새 모델과
    # 호흡을 맞추는 첫 시간에 열다섯 집이 동시에 노출되지 않게 (GLG, 2026-09-15:
    # "간단한 시작을 맡겨봐야하는데 … 일반적인 스위퍼하는 역할부터").
    # 대장을 고치는 것이 아니므로 다음 `on` 은 다시 전부가 기본이다.
    if only:
        wanted = {o.strip() for o in only.split(",") if o.strip()}
        picked = [r for r in allow_repos if r in wanted or r.split("/")[-1] in wanted]
        unknown = sorted(wanted - set(picked) - {r.split("/")[-1] for r in picked})
        if unknown:
            raise Halt(
                f"--only names repos that are not reachable targets: {', '.join(unknown)}\n"
                f"     reachable right now: {', '.join(allow_repos)}"
            )
        print(f"   --only → narrowed this start to {len(picked)}/{len(allow_repos)}: {','.join(picked)}")
        print("     (the ledger is untouched — the next `on` without --only is all of them again)")
        allow_repos = picked

    print("\n5) resolve paths (absolute — relative paths break because the worktree pool resolves them against cwd)")
    workspace_root = DATA_DIR / "workspaces"
    sqlite_path = DATA_DIR / "robomp.sqlite"
    app_log_dir = DATA_DIR / "logs"
    natives_root = DATA_DIR / "cache" / "pi-natives"
    for p in (workspace_root, sqlite_path.parent, app_log_dir, natives_root):
        print(f"   {'would create' if dry else 'creating'}: {p}")
        if not dry:
            p.mkdir(parents=True, exist_ok=True)

    print("\n6) config file: " + str(ROBOMP_ENV))
    existing = parse_env_file(ROBOMP_ENV)
    webhook_secret = existing.get("GITHUB_WEBHOOK_SECRET") or secrets.token_hex(32)
    hmac_key = existing.get("ROBOMP_GH_PROXY_HMAC_KEY") or secrets.token_hex(32)
    print(f"   GITHUB_WEBHOOK_SECRET     {'reused' if 'GITHUB_WEBHOOK_SECRET' in existing else 'newly generated'} (value not printed)")
    print(f"   ROBOMP_GH_PROXY_HMAC_KEY  {'reused' if 'ROBOMP_GH_PROXY_HMAC_KEY' in existing else 'newly generated'} (value not printed)")
    provider_key = os.environ.get(PROVIDER_KEY_ENV, "") or existing.get(PROVIDER_KEY_ENV, "")
    if not provider_key and not dry:
        raise Halt(
            f"{PROVIDER_KEY_ENV} is missing — can't run with {MODEL}.\n"
            f"     the child omp starts in an isolated XDG and can't see the host subscription (agent.db). "
            f"put the key in your shell and re-run `on`: export {PROVIDER_KEY_ENV}=..."
        )
    print(f"   {PROVIDER_KEY_ENV}            {'read from environment' if os.environ.get(PROVIDER_KEY_ENV) else ('reused from existing file' if provider_key else 'missing')} (value not printed)")
    values = {
        "GITHUB_WEBHOOK_SECRET": webhook_secret,
        "ROBOMP_BOT_LOGIN": BOT_LOGIN,
        # config.py 의 orchestrator Settings 는 이 둘을 필수로 요구한다
        # (`git_author_email: str = Field(..., ...)`, 기본값 없음). stock full
        # 프로파일은 gh_push_branch 를 실제로 쓰므로 여기 값이 커밋 저자가 된다.
        "ROBOMP_GIT_AUTHOR_NAME": existing.get("ROBOMP_GIT_AUTHOR_NAME", "sorge-robomp"),
        "ROBOMP_GIT_AUTHOR_EMAIL": existing.get("ROBOMP_GIT_AUTHOR_EMAIL", "sorge-robomp@users.noreply.github.com"),
        "ROBOMP_MODEL": MODEL,
        "ROBOMP_THINKING": THINKING,
        # 자식 omp 는 격리 XDG 로 뜨고 호스트 `agent.db` 를 못 본다 (stock 은
        # agent_dir 설정 자체가 없다). 그래서 자격증명은 provider API 키 축뿐이고,
        # 이 키는 stock 의 scrub 목록(`worker.py:127-134`)에 없어서 자식까지 닿는다.
        PROVIDER_KEY_ENV: provider_key,
        "ROBOMP_REPO_ALLOWLIST": ",".join(allow_repos),
        "ROBOMP_GH_PROXY_URL": f"http://{PROXY_HOST}:{PROXY_PORT}",
        "ROBOMP_GH_PROXY_HMAC_KEY": hmac_key,
        "ROBOMP_WORKSPACE_ROOT": str(workspace_root),
        "ROBOMP_SQLITE_PATH": str(sqlite_path),
        "ROBOMP_LOG_DIR": str(app_log_dir),
        "ROBOMP_NATIVES_CACHE_ROOT": str(natives_root),
        # 나머지 동작은 stock 기본값을 그대로 둔다 — 우리가 값을 적는 순간
        # 그것이 관리 대상이 되고, omp 버전업 때 기본값 변화를 못 따라간다.
        # 예외 하나: 자동 close 는 GLG 의 이슈를 무인으로 닫으므로 끈다.
        "ROBOMP_QUESTION_AUTOCLOSE_ENABLED": "false",
        "ROBOMP_BIND_HOST": ORCH_HOST,
        "ROBOMP_BIND_PORT": str(ORCH_PORT),
    }
    for k, v in values.items():
        if k in SECRET_KEYS:
            continue
        print(f"   {k}={v}")
    if dry:
        print(f"   [dry-run] not writing {ROBOMP_ENV} (would become 0600)")
    else:
        write_env_file(ROBOMP_ENV, values)
        print(f"   ✓ wrote: {ROBOMP_ENV} (0600)")

    print("\n7) config file: " + str(PROXY_ENV))
    if dry:
        print(f"   [dry-run] not writing {PROXY_ENV} (0600, would hold only GITHUB_TOKEN — already read and checked in step 4)")
    else:
        write_env_file(PROXY_ENV, {"GITHUB_TOKEN": bot_token})
        print(f"   ✓ wrote: {PROXY_ENV} (0600, GITHUB_TOKEN only)")

    print("\n8) port check")
    check(dry, not port_alive(PROXY_HOST, PROXY_PORT), f"{PROXY_HOST}:{PROXY_PORT} free", f"{PROXY_HOST}:{PROXY_PORT} already in use — run `off` first or check that process")
    check(dry, not port_alive(ORCH_HOST, ORCH_PORT), f"{ORCH_HOST}:{ORCH_PORT} free", f"{ORCH_HOST}:{ORCH_PORT} already in use — run `off` first or check that process")

    print("\n9) gh-proxy startup")
    proxy_cmd = [pyexe, "-m", "robomp.proxy", "serve"]
    proxy_log = LOG_DIR / "gh-proxy.log"
    print(f"   {'would launch' if dry else 'launching'}: {' '.join(shlex.quote(c) for c in proxy_cmd)}")
    print(f"     cwd={robomp_src}")
    print(f"     env: GITHUB_TOKEN(proxy only) · ROBOMP_GH_PROXY_HMAC_KEY · ROBOMP_WORKSPACE_ROOT · ROBOMP_LOG_DIR")
    print(f"     bind: ROBOMP_GH_PROXY_BIND_HOST={PROXY_HOST} ROBOMP_GH_PROXY_BIND_PORT={PROXY_PORT}")
    print(f"     log: {proxy_log}  pidfile: {pidfile_path('gh-proxy')}")
    print(f"     readiness check: successful connection to {PROXY_HOST}:{PROXY_PORT} (up to 30s)")
    if not dry:
        proxy_env = dict(os.environ)
        proxy_env.update(parse_env_file(ROBOMP_ENV))  # HMAC key, workspace/log 경로 공유
        proxy_env.update(parse_env_file(PROXY_ENV))  # GITHUB_TOKEN
        proxy_env["ROBOMP_GH_PROXY_BIND_HOST"] = PROXY_HOST
        proxy_env["ROBOMP_GH_PROXY_BIND_PORT"] = str(PROXY_PORT)
        launch(proxy_cmd, cwd=robomp_src, env=proxy_env, log_path=proxy_log, pidname="gh-proxy")
        wait_port(PROXY_HOST, PROXY_PORT, 30, "gh-proxy")

    print("\n10) orchestrator startup")
    orch_cmd = [pyexe, "-m", "robomp", "serve"]
    orch_log = LOG_DIR / "orchestrator.log"
    print(f"   {'would launch' if dry else 'launching'}: {' '.join(shlex.quote(c) for c in orch_cmd)}")
    print(f"     cwd={robomp_src}  env: all of {ROBOMP_ENV} (GITHUB_TOKEN withheld — serve rejects it)")
    print(f"     bind: ROBOMP_BIND_HOST={ORCH_HOST} ROBOMP_BIND_PORT={ORCH_PORT}")
    print(f"     log: {orch_log}  pidfile: {pidfile_path('orchestrator')}")
    print(f"     readiness check: GET http://{ORCH_HOST}:{ORCH_PORT}/healthz (up to 30s)")
    if not dry:
        orch_env = dict(os.environ)
        orch_env.update(parse_env_file(ROBOMP_ENV))
        orch_env.pop("GITHUB_TOKEN", None)  # serve() 가 이걸 보면 SystemExit — 절대 안 준다
        launch(orch_cmd, cwd=robomp_src, env=orch_env, log_path=orch_log, pidname="orchestrator")
        wait_http_ok(f"http://{ORCH_HOST}:{ORCH_PORT}/healthz", 30, "orchestrator")

    print(f"\n11) gh webhook forward ({len(allow_repos)} repos, --events=issues)")
    classic_pat = attempt(dry, f"pass {PASS_PAT_CLASSIC} read (admin:repo_hook, forward only)", lambda: pass_show(PASS_PAT_CLASSIC))
    for repo in allow_repos:
        stale = forwarder_hooks(classic_pat, repo) if classic_pat else []
        for hook_id in stale:
            # `gh webhook forward` 는 repo 에 relay 훅을 만들고, 프로세스가
            # 죽어도 그 훅을 남긴다. 다음 `on` 은 그걸 보고
            # `422 Hook already exists` 로 즉사한다 — 켜기 전에 우리가 만든
            # 훅만 지운다(다른 훅은 건드리지 않는다).
            print(f"   {'would delete' if dry else 'deleting'}: {repo}'s leftover forwarder hook {hook_id}")
            if not dry:
                status, _ = gh_api(classic_pat, "DELETE", f"/repos/{repo}/hooks/{hook_id}")
                if status not in (204, 404):
                    raise Halt(f"{repo} forwarder hook {hook_id} deletion failed ({status})")
    for repo in allow_repos:
        name = forward_name(repo)
        fwd_log = LOG_DIR / f"{name}.log"
        printable = [
            "gh", "webhook", "forward",
            f"--repo={repo}", "--events=issues",
            f"--url=http://{ORCH_HOST}:{ORCH_PORT}/webhook/github",
            "--secret=***",
        ]
        print(f"   {'would launch' if dry else 'launching'}: {' '.join(printable)}")
        print(f"     env: GH_TOKEN=<forge classic PAT>  log: {fwd_log}  pidfile: {pidfile_path(name)}")
        print(f"     readiness check: forward/listen signal in the log (up to 20s)")
        if not dry:
            real_cmd = [
                "gh", "webhook", "forward",
                f"--repo={repo}", "--events=issues",
                f"--url=http://{ORCH_HOST}:{ORCH_PORT}/webhook/github",
                f"--secret={webhook_secret}",
            ]
            fwd_env = dict(os.environ)
            fwd_env["GH_TOKEN"] = classic_pat
            launch(real_cmd, cwd=robomp_src, env=fwd_env, log_path=fwd_log, pidname=name)
            wait_log(fwd_log, re.compile(r"[Ff]orward|[Ll]isten|[Cc]onnect"), 20, name)

    print()
    if dry:
        print("dry-run done — to actually turn it on: `./run.sh robomp on --go`")
    else:
        print("✓ started. Check with `./run.sh robomp status`.")


def cmd_on(args):
    dry = not args.go
    print(f"━━ sorge robomp · on · {'dry-run (add --go to actually run)' if dry else 'run'} ━━\n")
    try:
        _on_steps(dry, getattr(args, "only", "") or "")
    except Halt as exc:
        print(f"\nhalted: {exc}")
        sys.exit(1)


# ── off ──────────────────────────────────────────────────────────────────


def cmd_off(_args):
    print("━━ sorge robomp · off ━━\n")
    cfg = parse_env_file(ROBOMP_ENV)
    repos = [r for r in cfg.get("ROBOMP_REPO_ALLOWLIST", "").split(",") if r]
    names = ["orchestrator", "gh-proxy"] + [forward_name(r) for r in repos]
    # 대장이 줄어든 뒤에도 남았을 pidfile 을 놓치지 않는다.
    if STATE_DIR.exists():
        for p in STATE_DIR.glob("webhook-forward-*.pid"):
            if p.stem not in names:
                names.append(p.stem)

    any_running = False
    for name in names:
        alive, pid = proc_alive(name)
        if not alive:
            continue
        any_running = True
        print(f"  {name}: SIGTERM → pid {pid}")
        try:
            os.kill(pid, signal.SIGTERM)
        except ProcessLookupError:
            pass
        for _ in range(20):
            if not pid_alive(pid):
                break
            time.sleep(0.5)
        if pid_alive(pid):
            print("    not dying → SIGKILL")
            try:
                os.kill(pid, signal.SIGKILL)
            except ProcessLookupError:
                pass
        print("    ✓ stopped")
        pidfile_path(name).unlink(missing_ok=True)

    # 프로세스를 내려도 GitHub 쪽 relay 훅은 남는다. 남기면 배달이 아무도
    # 안 받는 곳으로 흐르고, 다음 `on` 은 `422 Hook already exists` 로 죽는다.
    if repos:
        try:
            classic_pat = pass_show(PASS_PAT_CLASSIC)
        except RuntimeError as exc:
            print(f"  · could not clean up relay hooks — {exc}")
        else:
            for repo in repos:
                for hook_id in forwarder_hooks(classic_pat, repo):
                    status, _ = gh_api(classic_pat, "DELETE", f"/repos/{repo}/hooks/{hook_id}")
                    mark = "✓" if status in (204, 404) else f"✗({status})"
                    print(f"  {mark} {repo} relay hook {hook_id} deleted")

    if not any_running:
        print("  process was already stopped.")


# ── judge ────────────────────────────────────────────────────────────────


def cmd_judge(args):
    """이슈 하나를 손으로 판정 큐에 넣는다 — 웹훅이 온 것처럼.

    사건을 기다리지 않고 지금 판정을 보고 싶을 때, 그리고 훅이 끊겼던 동안
    지나간 이슈를 따라잡을 때 쓴다. 판정 자체는 도는 orchestrator 가 한다 —
    이 명령은 줄에 세우고 빠진다.
    """
    print(f"━━ sorge robomp · judge {args.ref} ━━\n")
    alive, _ = proc_alive("orchestrator")
    if not alive:
        print("  ✗ orchestrator is not up — run `./run.sh robomp on --go` first")
        sys.exit(1)
    cfg = parse_env_file(ROBOMP_ENV)
    if not cfg:
        print(f"  ✗ {ROBOMP_ENV} is missing — run `./run.sh robomp on --go` first")
        sys.exit(1)
    env = dict(os.environ)
    env.update(cfg)
    env.pop("GITHUB_TOKEN", None)  # orchestrator 쪽 설정이다 — PAT 는 gh-proxy 만 든다
    pyexe = str(VENV_DIR / "bin" / "python")
    r = subprocess.run([pyexe, "-m", "robomp", "triage", args.ref], cwd=str(omp_root() / "python" / "robomp"), env=env)
    if r.returncode != 0:
        sys.exit(r.returncode)
    print("\n  ✓ queued. Follow along in the log:")
    print(f"    tail -f {LOG_DIR / 'orchestrator.log'}")


# ── main ─────────────────────────────────────────────────────────────────


def main():
    ap = argparse.ArgumentParser(description="sorge robomp — issue hook loop ON switch")
    sub = ap.add_subparsers(dest="cmd")
    sub.add_parser("status", help="gh-proxy/orchestrator/webhook forward liveness + allowlist + recent events")
    sub.add_parser("allowlist", help="LEDGER.md-assigned repos → owner/repo list (reuses board.ledger_houses)")
    p_on = sub.add_parser("on", help="turns on in order: venv → env file → gh-proxy → orchestrator → webhook forward")
    p_on.add_argument("--go", action="store_true", help="actually turn it on (default is dry-run — prints the plan only, no side effects)")
    p_on.add_argument(
        "--only",
        default="",
        metavar="REPO[,REPO]",
        help="narrow THIS start to a few repos (ledger stays untouched; short names ok, e.g. --only sorge)",
    )
    sub.add_parser("off", help="gracefully stops everything by pidfile (SIGTERM → check → SIGKILL)")
    p_judge = sub.add_parser("judge", help="manually queue one issue for judging (doesn't wait for a webhook)")
    p_judge.add_argument("ref", help="owner/repo#NN — must be a ledger target and inside the allowlist")
    a = ap.parse_args()

    if a.cmd == "status":
        cmd_status(a)
    elif a.cmd == "allowlist":
        cmd_allowlist(a)
    elif a.cmd == "on":
        cmd_on(a)
    elif a.cmd == "off":
        cmd_off(a)
    elif a.cmd == "judge":
        cmd_judge(a)
    else:
        ap.print_help()


if __name__ == "__main__":
    main()
